CPWindow4::CPWindow4(void)
{
  SetFOwner(this);
  SetClass(wxT("CPWindow"));
  SetName(wxT("window4"));
  SetTag(0);
  SetX(58);
  SetY(212);
  SetWidth(179);
  SetHeight(420);
  SetHint(wxT(""));
  SetEnable(1);
  SetVisible(1);
  SetPopupMenu(NULL);
  SetTitle(wxT("Events"));
  SetOverrideRedirect(0);
};
