CPWindow3::CPWindow3(void)
{
  SetFOwner(this);
  SetClass(wxT("CPWindow"));
  SetName(wxT("window3"));
  SetTag(0);
  SetX(13);
  SetY(260);
  SetWidth(194);
  SetHeight(382);
  SetHint(wxT(""));
  SetEnable(1);
  SetVisible(1);
  SetPopupMenu(NULL);
  SetTitle(wxT("Propierties"));
  SetOverrideRedirect(0);
};
