CPWindow1::CPWindow1(void)
{
  SetFOwner(this);
  SetClass(wxT("CPWindow"));
  SetName(wxT("window1"));
  SetTag(0);
  SetX(259);
  SetY(138);
  SetWidth(954);
  SetHeight(629);
  SetHint(wxT(""));
  SetEnable(1);
  SetVisible(1);
  SetPopupMenu(NULL);
  SetTitle(wxT("imageview"));
  SetOverrideRedirect(0);
  //draw1
  draw1.SetFOwner(this);
  draw1.SetClass(wxT("CImage"));
  draw1.SetName(wxT("draw1"));
  draw1.SetTag(0);
  draw1.SetX(292);
  draw1.SetY(25);
  draw1.SetWidth(645);
  draw1.SetHeight(510);
  draw1.SetHint(wxT(""));
  draw1.SetEnable(1);
  draw1.SetVisible(1);
  draw1.SetPopupMenu(NULL);
  draw1.SetTransparent(1);
  draw1.SetImgFileName(wxT(""));
  CreateChild(&draw1);
  //filelist1
  filelist1.SetFOwner(this);
  filelist1.SetClass(wxT("CFileList"));
  filelist1.SetName(wxT("filelist1"));
  filelist1.SetTag(0);
  filelist1.SetX(25);
  filelist1.SetY(24);
  filelist1.SetWidth(250);
  filelist1.SetHeight(516);
  filelist1.SetHint(wxT(""));
  filelist1.SetEnable(1);
  filelist1.SetVisible(1);
  filelist1.SetPopupMenu(NULL);
  filelist1.SetDir(wxT(""));
  filelist1.EvFileListSelectFile=EVFILELISTSELECTFILE & CPWindow1::filelist1_EvFileListSelectFile;
  CreateChild(&filelist1);
  //menu1
  menu1.SetFOwner(this);
  menu1.SetClass(wxT("CMenu"));
  menu1.SetName(wxT("menu1"));
  menu1.SetTag(0);
  menu1.SetMenuItems(wxT("File,Help,"));
  CreateChild(&menu1);
  //menu1_File
  menu1_File.SetFOwner(this);
  menu1_File.SetClass(wxT("CPMenu"));
  menu1_File.SetName(wxT("menu1_File"));
  menu1_File.SetTag(0);
  menu1_File.SetText(wxT("File"));
  menu1_File.SetMenuItems(wxT("Exit,"));
  menu1.CreateChild(&menu1_File);
  //menu1_Help
  menu1_Help.SetFOwner(this);
  menu1_Help.SetClass(wxT("CPMenu"));
  menu1_Help.SetName(wxT("menu1_Help"));
  menu1_Help.SetTag(0);
  menu1_Help.SetText(wxT("Help"));
  menu1_Help.SetMenuItems(wxT("About,"));
  menu1.CreateChild(&menu1_Help);
  //menu1_File_Exit
  menu1_File_Exit.SetFOwner(this);
  menu1_File_Exit.SetClass(wxT("CItemMenu"));
  menu1_File_Exit.SetName(wxT("menu1_File_Exit"));
  menu1_File_Exit.SetTag(0);
  menu1_File_Exit.SetText(wxT("Exit"));
  menu1_File_Exit.SetSubMenu(NULL);
  menu1_File_Exit.EvMenuActive=EVMENUACTIVE & CPWindow1::menu1_File_Exit_EvMenuActive;
  menu1_File.CreateChild(&menu1_File_Exit);
  //menu1_Help_About
  menu1_Help_About.SetFOwner(this);
  menu1_Help_About.SetClass(wxT("CItemMenu"));
  menu1_Help_About.SetName(wxT("menu1_Help_About"));
  menu1_Help_About.SetTag(0);
  menu1_Help_About.SetText(wxT("About"));
  menu1_Help_About.SetSubMenu(NULL);
  menu1_Help_About.EvMenuActive=EVMENUACTIVE & CPWindow1::menu1_Help_About_EvMenuActive;
  menu1_Help.CreateChild(&menu1_Help_About);
  /*#Others*/
}
